-- Run this in your Supabase SQL Editor
-- This strictly adheres to the "Addition-Only" approach by creating isolated tables without touching existing ones.

CREATE TABLE IF NOT EXISTS event_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(50) NOT NULL,
    athlete_id VARCHAR(50) NOT NULL,
    club_name VARCHAR(100), 
    check_in_date DATE NOT NULL,
    check_in_time TIMESTAMP WITH TIME ZONE NOT NULL,
    scanner_location VARCHAR(100),
    scan_count INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Prevents multiple check-ins for the same athlete on the same day for an event
    UNIQUE(event_id, athlete_id, check_in_date)
);

-- Basic indexes for performance
CREATE INDEX IF NOT EXISTS idx_event_attendance_date ON event_attendance(event_id, check_in_date);

-- Enable RLS (open access for the anon key to match existing simple frontend architecture, or restrict as needed)
ALTER TABLE event_attendance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public inserts" ON event_attendance
FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public select" ON event_attendance
FOR SELECT USING (true);

CREATE POLICY "Allow public update" ON event_attendance
FOR UPDATE USING (true);
